# Managed by chezmoi. Dimidium terminal palette for Termux.
# Source: https://github.com/dofuuz/dimidium

foreground=#BAB7B6
background=#141414
cursor=#BAB7B6

color0=#000000
color1=#CF494C
color2=#60B442
color3=#DB9C11
color4=#0575D8
color5=#AF5ED2
color6=#1DB6BB
color7=#BAB7B6
color8=#817E7E
color9=#FF643B
color10=#37E57B
color11=#FCCD1A
color12=#688DFD
color13=#ED6FE9
color14=#32E0FB
color15=#DEE3E4
